name: Cebuano
favicon: null
layout_spectrum: 0.3444347931072116
typography_spectrum: 0.011738065164536238
title: "Cebuano's Albion Online Adventures"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6589398754294962
  lightness: 0.6111354592721909
  saturation: 0.8508691512979567
  rhythmicContrast: 0.18467268534004688
purpose: []
